### DISCUSSION TITLE
Ensuring the provider has reached the pickup location

### DISCUSSION THREAD

**Discussion by rajtechieaid** [beckn/mobility#46] [Q&A]
Is there a way for the driver and passenger to confirm if the driver has reached and started the ride using a OTP mechanism? Also how would you ensure that passenger has confirmed that he/she has reached the dropped location, so the driver could end/complete the ride?

**Comment by ravi-prakash-v** [comment]
Yes, the `Stop` schema has a property called `authorization` which is of type `Authorization`

Below is the schema for your reference.

```
Authorization:
      description: 'Describes an authorization mechanism used to start or end the fulfillment of an order. For example, in the mobility sector, the driver may require a one-time password to initiate the ride. In the healthcare sector, a patient may need to provide a password to open a video conference link during a teleconsultation.'
      type: object
      properties:
        type:
          description: Type of authorization mechanism used. The allowed values for this field can be published as part of the network policy.
          type: string
        token:
          description: 'Token used for authorization. This is typically generated at the BPP. The BAP can send this value to the user via any channel that it uses to authenticate the user like SMS, Email, Push notification, or in-app rendering.'
          type: string
        valid_from:
          description: Timestamp in RFC3339 format from which token is valid
          type: string
          format: date-time
        valid_to:
          description: Timestamp in RFC3339 format until which token is valid
          type: string
          format: date-time
        status:
          description: Status of the token
          type: string
```

When the order is confirmed, the BPP will pass this object in the `on_confirm` callback. A sample `on_confirm` request with the OTP mechanism is shown below


```
{
    "context": {
        "action": "on_confirm",
        "bap_id": "<FQDN of BAP>",
        "bap_uri": "<Callback URL containing FQDN of BAP>",
        "bpp_id": "<FQDN of BPP>",
        "bpp_uri": "<Request URL containing FQDN of BPP>",
        "domain": "nic2004:60221",
        "location": {
            "city": {
                "code": "std:0816"
            },
            "country": {
                "code": "IND"
            }
        },
        "version": "1.0.0",
        "timestamp": "2023-03-03T06:13:43.466Z",
        "transaction_id": "b04ac362-cd1b-4dcd-a59b-2efa3c5f7820",
        "message_id": "d78090cb-3dac-41f1-bfef-1f66e603c8e3",
        "ttl": "PT3M"
    },
    "message": {
        "order": {
            "id": "ABCD1234",
            "provider": {
                "descriptor": {
                    "name": "<name of mobility service provider>"
                }
            },
            "items": [
                {
                    "id": "1",
                    "descriptor": {
                        "name": "Auto ride",
                        "code": "RIDE"
                    },
                    "price": {
                        "currency": "INR",
                        "value": "105"
                    },
                    "tags": [
                        {
                            "descriptor": {
                                "name": "Fare Policy",
                                "code": "fare_policy"
                            },
                            "list": [
                                {
                                    "descriptor": {
                                        "name": "Base Fare",
                                        "code": "min_fare"
                                    },
                                    "value": "30 INR"
                                },
                                {
                                    "descriptor": {
                                        "name": "Base fare upto",
                                        "code": "min_fare_dist"
                                    },
                                    "value": "1 km"
                                },
                                {
                                    "descriptor": {
                                        "name": "Fare above base fare",
                                        "code": "fare_per_dist"
                                    },
                                    "value": "12 INR / km"
                                },
                                {
                                    "descriptor": {
                                        "name": "Waiting Charges",
                                        "code": "waiting_charges"
                                    },
                                    "value": "2 INR / min"
                                },
                                {
                                    "value": "All prices inclusive of GST"
                                }
                            ]
                        }
                    ]
                }
            ],
            "billing": {
                "name": "John Doe",
                "phone": "+91-9999999999"
            },
            "fulfillments": [
                {
                    "customer": {
                        "person": {
                            "name": "John Doe",
                            "phone": "+91-9999999999"
                        }
                    },
                    "state": {
                        "descriptor": {
                            "name": "Driver has been assigned",
                            "code": "AGENT-ASSIGNED"
                        }
                    },
                    "stops": [
                        {
                            "id": "1",
                            "location": {
                                "gps": "13.37627117,77.11683433",
                                "address": "Tower B, Purva Westend Apartment, No 26, Hosur Road, Bengaluru - 560068"
                            },
                            "authorization": {
                                "type": "otp",
                                "token": "123456",
                                "status": "unverified"
                            }
                        },
                        {
                            "id": "2",
                            "parent_stop_id": "1",
                            "location": {
                                "gps": "13.3802153,77.1115573",
                                "address": "Salarpuria Greenage Birch Block, No 7, Hosur Road, Bengaluru - 560069"
                            }
                        }
                    ],
                    "agent": {
                        "person": {
                            "name": "Manjunath",
                            "phone": "+919669669669"
                        }
                    },
                    "vehicle": {
                        "category": "AUTO_RICKSHAW",
                        "registration": "KA01JG1231"
                    },
                    "tracking": false
                }
            ],
            "payments": [
                {
                    "id": "1",
                    "collected_by": "BPP",
                    "type": "ON-FULFILLMENT",
                    "params": {
                        "amount": "105",
                        "currency": "INR"
                    },
                    "status": "NOT-PAID"
                }
            ],
            "quote": {
                "price": {
                    "currency": "INR",
                    "value": "105"
                },
                "breakup": [
                    {
                        "title": "Ride Fare",
                        "price": {
                            "currency": "INR",
                            "value": "100"
                        }
                    },
                    {
                        "title": "CGST @ 2.5%",
                        "price": {
                            "currency": "INR",
                            "value": "2.5"
                        }
                    },
                    {
                        "title": "SGST @ 2.5%",
                        "price": {
                            "currency": "INR",
                            "value": "2.5"
                        }
                    }
                ],
                "ttl": "PT3M"
            }
        }
    }
}
```

If you notice, the `message.order.fulfillments[0].stops[0].authorization` contains the OTP that is shown to the customer. 

The customer can then provide the OTP to the driver and he can verify the ride. 

Hope this helps.
